version: '3'

services:
  database:
    image: mysql:8.3.0
    restart: on-failure
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_DATABASE=task_db"
      - "MYSQL_ROOT_PASSWORD=root1234"
    volumes:
      - ./src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      backend:
        aliases:
          - "database"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: ladzislau/task-management-system:0.0.1-SNAPSHOT
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - backend

networks:
  backend:
    driver: bridge