FROM maven:3.8.4-openjdk-17 AS development

WORKDIR /app

EXPOSE 8080

COPY pom.xml .

RUN mvn dependency:go-offline

COPY src ./src

RUN mvn clean package

CMD ["java", "-jar", "/app/target/task-management-system-0.0.1-SNAPSHOT.jar"]