FROM maven:3.8.4-openjdk-17 AS builder

WORKDIR /app

COPY pom.xml .

RUN mvn dependency:go-offline

COPY src ./src

RUN mvn clean package

FROM maven:3.8.4-openjdk-17 AS development

WORKDIR /app

COPY --from=builder /app/target/task-management-system-0.0.1-SNAPSHOT.jar .
